GET http://localhost:8080/odata/v4/NetworkObjectsService/$metadata

###
GET http://localhost:8080/odata/v4/NetworkObjectsService/NetworkObjects

###
POST http://localhost:8080/odata/v4/NetworkObjectsService/NetworkObjects
Content-Type: application/json

{
    "network_object_description" : "Meter Object",
    "network_object_type": "METER"
}

###
POST http://localhost:8080/odata/v4/NetworkObjectsService/NetworkObjectTypes
Content-Type: application/json

{
    "network_object_type_description" : "Clusters for PN",
    "network_object_type": "CLUSTER"
}

###
GET http://localhost:8080/odata/v4/NetworkObjectsService/NetworkObjectTypes