spring:
  web.resources.static-locations: "file:./app/webapp"
  config.activate.on-profile: cloud



cds:
  security.mock.users:
   - name: admin
     password: admin
     roles:
     - admin  
   - name: user
     password: user