spring:
  web.resources.static-locations: "file:./app/webapp"
  config.activate.on-profile: sqlite
  datasource:
    url: "jdbc:sqlite:/home/user/projects/UOMonCloud_POC_NO/sqlite.db"
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 1
  sql:
    init:
      mode: never  # originally the value was always ..but since cds model created already changed to never


cds:
  security.mock.users:
   - name: admin
     password: admin
     roles:
     - admin  
   - name: user
     password: user